from config.common_config import CommonConfig


class OnlineAnomalyDetectionConfig(CommonConfig):
    """在线异常检测与门控配置"""

    EXPERIMENT_NAME = "online_anomaly_detection"

    # 输入特征
    FEATURE_COLUMNS = ["CL", "Twb", "CL_predict"]

    # StreamingAnomalyGate
    GATE_LOCAL_WINDOW_SIZE = 135
    GATE_GLOBAL_EMA_DECAY = 0.0625
    GATE_REFERENCE_SAMPLES = 700
    GATE_ALPHA_LOCAL_WEIGHT = 0.675
    GATE_THRESHOLD_BIAS = -0.043057734706757875
    GATE_SCORE_SHORT_WEIGHT = 0.55
    GATE_SCORE_MEDIUM_WEIGHT = 0.275
    GATE_SCORE_LONG_WEIGHT = 0.175
    GATE_TRIGGER_HYSTERESIS_MARGIN = 0.021759826420260316
    GATE_MIN_TRIGGER_INTERVAL = 1

    # Gate sensitivity analysis
    GATE_SENSITIVITY_BOOTSTRAP_SAMPLES = 500
    GATE_SENSITIVITY_BOOTSTRAP_BLOCK_SIZE = 48
    GATE_SENSITIVITY_BOOTSTRAP_SEED = 42
    GATE_SENSITIVITY_CONFIDENCE_LEVEL = 0.95
    GATE_SENSITIVITY_SIGNIFICANCE_LEVEL = 0.05
    GATE_SENSITIVITY_ROUND_LENGTH_STEPS = 288

    # StreamingStats
    STATS_EMA_DECAY = 0.01
    STATS_WINDOW_SIZE = 1000

    # StreamingIsolationDepth
    ISOLATION_UPDATE_FREQ = 50

    # StreamingThresholdOptimizer
    THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION = 70
    THRESHOLD_QUANTILE = 0.6675415126464518
    THRESHOLD_MAD_SCALE = 1.1352750910681282
    THRESHOLD_LOCAL_UPDATE_RATE = 0.5956588562510114
    THRESHOLD_QUANTILE_WEIGHT = 0.575

    # Gate 超参优化配置 - 多阶段分层优化
    GATE_OPTIMIZATION_SAMPLER = "tpe"
    GATE_OPTIMIZATION_SEED = 42
    GATE_OPTIMIZATION_DEFAULT_TRIALS = 150
    GATE_OPTIMIZATION_DEFAULT_N_JOBS = 1
    GATE_OPTIMIZATION_PHASE = "phase2"  # 可选: phase1, phase2, phase3
    GATE_OPTIMIZATION_PHASE1_TRIALS = 60  # Layer A: 核心决策参数
    GATE_OPTIMIZATION_PHASE2_TRIALS = 50  # Layer B: 自适应参数
    GATE_OPTIMIZATION_PHASE3_TRIALS = 40  # Layer C+D: 融合与风格参数
    GATE_OPTIMIZATION_PHASE_RANGE_SHRINK_RATIO = 0.2  # Phase 2/3 搜索范围缩小比例（±20%）
    GATE_OPT_BASELINE_FIXED_INTERVAL = 1
    GATE_OPT_REWARD_DROP_TOLERANCE_RATIO = 0.02
    GATE_OPT_ENERGY_INCREASE_TOLERANCE_RATIO = 0.01
    GATE_OPT_REWARD_DROP_PENALTY_WEIGHT = 4.0
    GATE_OPT_ENERGY_INCREASE_PENALTY_WEIGHT = 4.0

    GATE_OPT_GLOBAL_EMA_DECAY_MIN = 0.005
    GATE_OPT_GLOBAL_EMA_DECAY_MAX = 0.12
    GATE_OPT_ALPHA_LOCAL_WEIGHT_MIN = 0.4
    GATE_OPT_ALPHA_LOCAL_WEIGHT_MAX = 0.95
    GATE_OPT_LOCAL_WINDOW_SIZE_MIN = 30
    GATE_OPT_LOCAL_WINDOW_SIZE_MAX = 240
    GATE_OPT_REFERENCE_SAMPLES_MIN = 200
    GATE_OPT_REFERENCE_SAMPLES_MAX = 1200
    GATE_OPT_THRESHOLD_BIAS_MIN = -0.25
    GATE_OPT_THRESHOLD_BIAS_MAX = 0.10
    GATE_OPT_THRESHOLD_QUANTILE_MIN = 0.55
    GATE_OPT_THRESHOLD_QUANTILE_MAX = 0.90
    GATE_OPT_THRESHOLD_MAD_SCALE_MIN = 0.8
    GATE_OPT_THRESHOLD_MAD_SCALE_MAX = 2.8
    GATE_OPT_THRESHOLD_LOCAL_UPDATE_RATE_MIN = 0.1
    GATE_OPT_THRESHOLD_LOCAL_UPDATE_RATE_MAX = 0.8
    GATE_OPT_THRESHOLD_QUANTILE_WEIGHT_MIN = 0.2
    GATE_OPT_THRESHOLD_QUANTILE_WEIGHT_MAX = 0.95
    GATE_OPT_THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION_MIN = 20
    GATE_OPT_THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION_MAX = 120

    GATE_OPT_SCORE_SHORT_WEIGHT_MIN = 0.3
    GATE_OPT_SCORE_SHORT_WEIGHT_MAX = 0.8
    GATE_OPT_SCORE_MEDIUM_WEIGHT_MIN = 0.05
    GATE_OPT_SCORE_MEDIUM_WEIGHT_MAX = 0.5
    GATE_OPT_TRIGGER_HYSTERESIS_MARGIN_MIN = 0.0
    GATE_OPT_TRIGGER_HYSTERESIS_MARGIN_MAX = 0.12
