from config.common_config import CommonConfig


class OnlineAnomalyDetectionConfig(CommonConfig):
    """在线异常检测与门控配置"""

    EXPERIMENT_NAME = "online_anomaly_detection"

    # 输入特征
    FEATURE_COLUMNS = ["CL", "Twb", "CL_predict"]

    # OnlineFeatureEnhancer
    FEATURE_WINDOW_SIZES = [3, 5, 12, 24]

    # StreamingAnomalyGate
    GATE_LOCAL_WINDOW_SIZE = 187
    GATE_GLOBAL_EMA_DECAY = 0.0368
    GATE_REFERENCE_SAMPLES = 500
    GATE_CONTAMINATION = 0.2
    GATE_ALPHA_LOCAL_WEIGHT = 0.669
    GATE_THRESHOLD_BIAS = -0.106
    GATE_SCORE_SHORT_WEIGHT = 0.36
    GATE_SCORE_MEDIUM_WEIGHT = 0.40
    GATE_SCORE_LONG_WEIGHT = 0.23
    GATE_TRIGGER_HYSTERESIS_MARGIN = 0.020815156921978026
    GATE_MIN_TRIGGER_INTERVAL_STEPS = 1

    # StreamingStats
    STATS_EMA_DECAY = 0.01
    STATS_WINDOW_SIZE = 1000

    # StreamingIsolationDepth
    ISOLATION_UPDATE_FREQ = 50
    ISOLATION_DISTANCE_METRIC = "euclidean"
    ISOLATION_DECAY_STRATEGY = "FIFO"

    # StreamingThresholdOptimizer
    THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION = 30
    THRESHOLD_QUANTILE = 0.5799
    THRESHOLD_MAD_SCALE = 1.0146
    THRESHOLD_LOCAL_UPDATE_RATE = 0.7938
    THRESHOLD_QUANTILE_WEIGHT = 0.8996

    # Gate 超参优化配置
    GATE_OPTIMIZATION_SAMPLER = "tpe"
    GATE_OPTIMIZATION_SEED = 42
    GATE_OPTIMIZATION_DEFAULT_TRIALS = 120
    GATE_OPTIMIZATION_DEFAULT_N_JOBS = 1
    GATE_OPT_BASELINE_FIXED_INTERVAL = 1
    GATE_OPT_REWARD_DROP_TOLERANCE_RATIO = 0.02
    GATE_OPT_ENERGY_INCREASE_TOLERANCE_RATIO = 0.01
    GATE_OPT_REWARD_DROP_PENALTY_WEIGHT = 4.0
    GATE_OPT_ENERGY_INCREASE_PENALTY_WEIGHT = 4.0

    GATE_OPT_ALPHA_LOCAL_WEIGHT_MIN = 0.4
    GATE_OPT_ALPHA_LOCAL_WEIGHT_MAX = 0.95
    GATE_OPT_LOCAL_WINDOW_SIZE_MIN = 30
    GATE_OPT_LOCAL_WINDOW_SIZE_MAX = 240
    GATE_OPT_REFERENCE_SAMPLES_MIN = 200
    GATE_OPT_REFERENCE_SAMPLES_MAX = 1200
    GATE_OPT_CONTAMINATION_MIN = 0.05
    GATE_OPT_CONTAMINATION_MAX = 0.35
    GATE_OPT_THRESHOLD_QUANTILE_MIN = 0.55
    GATE_OPT_THRESHOLD_QUANTILE_MAX = 0.90
    GATE_OPT_THRESHOLD_MAD_SCALE_MIN = 0.8
    GATE_OPT_THRESHOLD_MAD_SCALE_MAX = 2.8
    GATE_OPT_THRESHOLD_LOCAL_UPDATE_RATE_MIN = 0.1
    GATE_OPT_THRESHOLD_LOCAL_UPDATE_RATE_MAX = 0.8
    GATE_OPT_THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION_MIN = 20
    GATE_OPT_THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION_MAX = 120

    GATE_OPT_SCORE_SHORT_WEIGHT_MIN = 0.3
    GATE_OPT_SCORE_SHORT_WEIGHT_MAX = 0.8
    GATE_OPT_SCORE_MEDIUM_WEIGHT_MIN = 0.05
    GATE_OPT_SCORE_MEDIUM_WEIGHT_MAX = 0.5
    GATE_OPT_TRIGGER_HYSTERESIS_MARGIN_MIN = 0.0
    GATE_OPT_TRIGGER_HYSTERESIS_MARGIN_MAX = 0.12
    GATE_OPT_MIN_TRIGGER_INTERVAL_STEPS_MIN = 1
    GATE_OPT_MIN_TRIGGER_INTERVAL_STEPS_MAX = 12

    # MultiScaleDistributionTracker
    TRACKER_WINDOWS = {
        "short": 100,
        "medium": 1440,
        "long": 10080,
    }
    TRACKER_EMA_DECAY = 0.01
