"""GateConfig 配置（frozen dataclass schema）。值由 YAML 提供（见 configs/）。"""
from __future__ import annotations

from dataclasses import dataclass

from et_prl.config.base import BaseConfig


@dataclass(frozen=True)
class GateConfig(BaseConfig):
    EXPERIMENT_NAME: str
    FEATURE_COLUMNS: list
    GATE_LOCAL_WINDOW_SIZE: int
    GATE_GLOBAL_EMA_DECAY: float
    GATE_REFERENCE_SAMPLES: int
    GATE_ALPHA_LOCAL_WEIGHT: float
    GATE_THRESHOLD_BIAS: float
    GATE_SCORE_SHORT_WEIGHT: float
    GATE_SCORE_MEDIUM_WEIGHT: float
    GATE_SCORE_LONG_WEIGHT: float
    GATE_TRIGGER_HYSTERESIS_MARGIN: float
    GATE_MIN_TRIGGER_INTERVAL: int
    GATE_SENSITIVITY_BOOTSTRAP_SAMPLES: int
    GATE_SENSITIVITY_BOOTSTRAP_BLOCK_SIZE: int
    GATE_SENSITIVITY_BOOTSTRAP_SEED: int
    GATE_SENSITIVITY_CONFIDENCE_LEVEL: float
    GATE_SENSITIVITY_SIGNIFICANCE_LEVEL: float
    GATE_SENSITIVITY_ROUND_LENGTH_STEPS: int
    STATS_EMA_DECAY: float
    STATS_WINDOW_SIZE: int
    ISOLATION_UPDATE_FREQ: int
    THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION: int
    THRESHOLD_QUANTILE: float
    THRESHOLD_MAD_SCALE: float
    THRESHOLD_LOCAL_UPDATE_RATE: float
    THRESHOLD_QUANTILE_WEIGHT: float
    GATE_OPTIMIZATION_SAMPLER: str
    GATE_OPTIMIZATION_SEED: int
    GATE_OPTIMIZATION_DEFAULT_TRIALS: int
    GATE_OPTIMIZATION_DEFAULT_N_JOBS: int
    GATE_OPTIMIZATION_PHASE: str
    GATE_OPTIMIZATION_PHASE1_TRIALS: int
    GATE_OPTIMIZATION_PHASE2_TRIALS: int
    GATE_OPTIMIZATION_PHASE3_TRIALS: int
    GATE_OPTIMIZATION_PHASE_RANGE_SHRINK_RATIO: float
    GATE_OPT_BASELINE_FIXED_INTERVAL: int
    GATE_OPT_REWARD_DROP_TOLERANCE_RATIO: float
    GATE_OPT_ENERGY_INCREASE_TOLERANCE_RATIO: float
    GATE_OPT_REWARD_DROP_PENALTY_WEIGHT: float
    GATE_OPT_ENERGY_INCREASE_PENALTY_WEIGHT: float
    GATE_OPT_GLOBAL_EMA_DECAY_MIN: float
    GATE_OPT_GLOBAL_EMA_DECAY_MAX: float
    GATE_OPT_ALPHA_LOCAL_WEIGHT_MIN: float
    GATE_OPT_ALPHA_LOCAL_WEIGHT_MAX: float
    GATE_OPT_LOCAL_WINDOW_SIZE_MIN: int
    GATE_OPT_LOCAL_WINDOW_SIZE_MAX: int
    GATE_OPT_REFERENCE_SAMPLES_MIN: int
    GATE_OPT_REFERENCE_SAMPLES_MAX: int
    GATE_OPT_THRESHOLD_BIAS_MIN: float
    GATE_OPT_THRESHOLD_BIAS_MAX: float
    GATE_OPT_THRESHOLD_QUANTILE_MIN: float
    GATE_OPT_THRESHOLD_QUANTILE_MAX: float
    GATE_OPT_THRESHOLD_MAD_SCALE_MIN: float
    GATE_OPT_THRESHOLD_MAD_SCALE_MAX: float
    GATE_OPT_THRESHOLD_LOCAL_UPDATE_RATE_MIN: float
    GATE_OPT_THRESHOLD_LOCAL_UPDATE_RATE_MAX: float
    GATE_OPT_THRESHOLD_QUANTILE_WEIGHT_MIN: float
    GATE_OPT_THRESHOLD_QUANTILE_WEIGHT_MAX: float
    GATE_OPT_THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION_MIN: int
    GATE_OPT_THRESHOLD_MIN_SAMPLES_FOR_OPTIMIZATION_MAX: int
    GATE_OPT_SCORE_SHORT_WEIGHT_MIN: float
    GATE_OPT_SCORE_SHORT_WEIGHT_MAX: float
    GATE_OPT_SCORE_MEDIUM_WEIGHT_MIN: float
    GATE_OPT_SCORE_MEDIUM_WEIGHT_MAX: float
    GATE_OPT_TRIGGER_HYSTERESIS_MARGIN_MIN: float
    GATE_OPT_TRIGGER_HYSTERESIS_MARGIN_MAX: float
